name: nustpulse

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nustpulse-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - nustpulse-network

  backend:
    build:
      context: ./nustpulse_backend
      dockerfile: docker/Dockerfile
    image: nustpulse-backend
    container_name: nustpulse-backend
    environment:
      - REDIS_URL=redis://nustpulse-redis:6379/0
    env_file:
      - ./nustpulse_backend/.env
    depends_on:
      - redis
    networks:
      - nustpulse-network

  frontend:
    build:
      context: ./nustpulse_frontend
      dockerfile: docker/Dockerfile
      args:
        - VITE_API_URL=/api
    image: nustpulse-frontend
    container_name: nustpulse-frontend
    networks:
      - nustpulse-network

  redis:
    image: redis:alpine
    container_name: nustpulse-redis
    networks:
      - nustpulse-network

  worker:
    build:
      context: ./nustpulse_backend
      dockerfile: docker/Dockerfile
    image: nustpulse-worker
    container_name: nustpulse-worker
    command: celery -A app.core.celery_app worker --loglevel=info
    environment:
      - REDIS_URL=redis://nustpulse-redis:6379/0
    env_file:
      - ./nustpulse_backend/.env
    depends_on:
      - redis
    networks:
      - nustpulse-network

  beat:
    build:
      context: ./nustpulse_backend
      dockerfile: docker/Dockerfile
    image: nustpulse-beat
    container_name: nustpulse-beat
    command: celery -A app.core.celery_app beat --loglevel=info
    environment:
      - REDIS_URL=redis://nustpulse-redis:6379/0
    env_file:
      - ./nustpulse_backend/.env
    depends_on:
      - redis
    networks:
      - nustpulse-network

networks:
  nustpulse-network:
    driver: bridge
