"""remove_section_add_is_pinned

Revision ID: b4cd4264bb6c
Revises: 69554d3280d4
Create Date: 2026-05-08 20:20:09.540251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4cd4264bb6c'
down_revision: Union[str, Sequence[str], None] = '69554d3280d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deadlines', sa.Column('is_pinned', sa.Boolean(), nullable=True))
    op.drop_column('users', 'section')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('section', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('deadlines', 'is_pinned')
    # ### end Alembic commands ###
