"""Add notification fields

Revision ID: da1efa9d107e
Revises: b4cd4264bb6c
Create Date: 2026-05-11 18:43:30.892761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da1efa9d107e'
down_revision: Union[str, Sequence[str], None] = 'b4cd4264bb6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deadlines', sa.Column('notified_new', sa.Boolean(), nullable=True))
    op.add_column('deadlines', sa.Column('last_reminder_sent_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('notification_email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('notifications_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notifications_enabled')
    op.drop_column('users', 'notification_email')
    op.drop_column('deadlines', 'last_reminder_sent_at')
    op.drop_column('deadlines', 'notified_new')
    # ### end Alembic commands ###
