"""pivot_to_nustpulse

Revision ID: 69554d3280d4
Revises: 5cc5dcfa96ed
Create Date: 2026-05-08 14:41:55.237197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69554d3280d4'
down_revision: Union[str, Sequence[str], None] = '5cc5dcfa96ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deadlines', sa.Column('course_name', sa.String(), nullable=True))
    op.add_column('deadlines', sa.Column('lms_event_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'deadlines', ['lms_event_id'])
    op.drop_column('deadlines', 'importance_level')
    op.drop_column('deadlines', 'estimated_effort')
    op.add_column('users', sa.Column('lms_username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('lms_password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('section', sa.String(), nullable=True))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['lms_username'])
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'section')
    op.drop_column('users', 'lms_password')
    op.drop_column('users', 'lms_username')
    op.add_column('deadlines', sa.Column('estimated_effort', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('deadlines', sa.Column('importance_level', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'deadlines', type_='unique')
    op.drop_column('deadlines', 'lms_event_id')
    op.drop_column('deadlines', 'course_name')
    # ### end Alembic commands ###
